
# Spring Boot configuration
spring:
  # profiles:
    # active: development
  # Security configuration
  # security:
    # user:
      # name: user
      # password: user
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: <clientId>
            clientSecret: <clientSecret> 
            scope: read:user,user:email
          facebook:
            client-id: <clientId> 
            client-secret: <clientSecret>
            scope: user_photo,email
          google:
            client-id: <clientId> 
            client-secret: <clientSecret>
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zulian
    username: root
    password: root
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  logging:
    level:
      org.springframework.web: DEBUG
      guru.springframework.controllers: DEBUG
      org.hibernate: DEBUG
      org: INFO
# Logger configuration
# logging:
#   pattern:
#     console: "%d %-5level %logger : %msg%n"
#   level:
#     org.springframework: info
#     org.hibernate: debug
# Server configuration
server:
  port: 9999 #set your port