
# Spring Boot configuration
spring:
  # profiles:
    # active: development
  # Security configuration
  # security:
    # user:
      # name: user
      # password: user
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: b270eb8db01a44f89169
            clientSecret: 81a2eb4e1a05b374e32f5cf3398cb2d7e80f7426 
            scope: read:user,user:email
          facebook:
            client-id: 1394666030888764 
            client-secret: edf72b566c209a6be8b9e31032b4f084 1048864095225-kr6vc9ghthfk3ocqln10pbr2n1sjqpkr.apps.googleusercontent.com
            scope: user_photo,email
          google:
            client-id: 1048864095225-kr6vc9ghthfk3ocqln10pbr2n1sjqpkr.apps.googleusercontent.com
            client-secret: YD9R59r9FTiBQQJBWoAecFaU
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zulian
    username: root
    password: root

    # # test env
    # url: jdbc:postgresql://postgresql-eco-innovation.alwaysdata.net/eco-innovation_e
    # username: eco-innovation	
    # password:	
    
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update #create-drop #update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  logging:
    level:
      org.springframework.web: DEBUG
      guru.springframework.controllers: DEBUG
      org.hibernate: DEBUG
      org: INFO
  graphiql:
     endpoint:
       subscriptions: /graphql
  # graphql:
  #   servlet:
  #     mapping: /graphql
  #     enabled: true
  #     corsEnabled: true
  #     websocket:
  #       enabled: true
  #       path: /graphql
  #     subscriptions:
  #       websocket:
  #         path: /graphql
# Logger configuration
# logging:
#   pattern:
#     console: "%d %-5level %logger : %msg%n"
#   level:
#     org.springframework: info
#     org.hibernate: debug
# Server configuration
server:
  port: 9999 #set your port